name: dmidecode # you probably want to 'snapcraft register <name>'
version: '3.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: snap to run dmidecode # 79 char long summary
description: |
  snap to run dmidecode using dmidecode version 3.1.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    run:
        command: usr/local/sbin/dmidecode
        plugs: [hardware-observe]
    biosdecode: 
        command: usr/local/sbin/biosdecode
        plugs: [hardware-observe]

parts:
    dmidecodegit:
        plugin: make
        source: git://anonscm.debian.org/collab-maint/dmidecode.git

